package io.repofyr.api.endpoint

import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.Route
import io.onfhir.api.FHIR_HTTP_OPTIONS
import io.onfhir.api.Resource
import io.onfhir.api.model.FHIRRequest
import io.repofyr.api.model.FHIRMarshallers._
import io.repofyr.api.service.FHIRBatchTransactionService
import io.repofyr.authz.AuthzManager
import io.onfhir.authz.{AuthContext, AuthzContext}
import io.repofyr.config.FhirConfigurationManager.{authzManager, targetResourceResolver}
import io.repofyr.config.OnfhirConfig

trait FHIRBatchTransactionEndpoint {

  // IMPORTANT! There is a bug for val definition of route if its path does not have any segment
  // so lazy val definition is used. The problem could be regenerated by converting lazy val to val
  // and then executing the tests. Moreover, in that case if you convert entity(as[Resource]) statement
  // to entity(as[String]) the problem dissapears.
  // Route definition of a bundle request
  def batchRoute(fhirRequest: FHIRRequest, authContext:(AuthContext, Option[AuthzContext])):Route = {
    pathEndOrSingleSlash {
      post {
          optionalHeaderValueByName(FHIR_HTTP_OPTIONS.PREFER) { prefer =>
            entity(as[Resource]) { resource =>
              //Set the bundle into the request
              fhirRequest.initializeTransactionOrBatchRequest(resource, OnfhirConfig.fhirEndpointSettings, prefer)
              targetResourceResolver.resolveTargetResource(fhirRequest) {
                //Enforce authorization
                authzManager.authorize(authContext._2, fhirRequest) {
                  //Execute the interaction
                  complete {
                    new FHIRBatchTransactionService().executeInteraction(fhirRequest, authContext._2)
                  }
                }
              }
            }
          }
      }
    }
  }
}
